// src-tauri/src/workspace/context.rs

use crate::agent::kind::AgentKind;

pub const MEMORY_PORT: u16 = 7547;

pub async fn rewrite_context(
    db:         &crate::db::Db,
    runbox_id:  &str,
    session_id: &str,
    cwd:        &str,
    agent:      &AgentKind,
) -> Result<(), String> {
    let content = build(db, runbox_id, session_id, cwd, agent).await?;
    let path    = std::path::Path::new(cwd).join(".stackbox-context.md");
    std::fs::write(&path, &content).map_err(|e| format!("write context: {e}"))?;
    Ok(())
}

pub async fn build(
    _db:        &crate::db::Db,
    runbox_id:  &str,
    session_id: &str,
    cwd:        &str,
    agent:      &AgentKind,
) -> Result<String, String> {
    let port       = MEMORY_PORT;
    let short_sid  = &session_id[..session_id.len().min(8)];
    let agent_name = agent.display_name();

    // ── Context injection: pull top memories ──────────────────────────────────
    let memory_block = if *agent != AgentKind::Shell {
        build_memory_context(runbox_id).await
    } else {
        String::new()
    };

    Ok(format!(
r#"# Stackbox Agent Instructions

> You are: **{agent_name}** · session `{short_sid}` · runbox `{runbox_id}`
> Working directory: `{cwd}`

{memory_block}
---

## Before You Start

Run this before editing any files:

```powershell
git add -A
```

This lets Stackbox track your changes (additions AND deletions).

---

## Saving Memories

After completing work, save a memory with this PowerShell command:

```powershell
Invoke-RestMethod -Uri "http://localhost:{port}/memory" -Method Post -ContentType "application/json" -Body (ConvertTo-Json @{{ runbox_id="{runbox_id}"; content="What you did, which files changed, any known issues." }})
```

Replace the `content` value with your actual summary (1–3 sentences).
Do NOT use `curl` or `memory_write` — use `Invoke-RestMethod` as shown above.

---

## Rules

- Always run `git add -A` before editing files
- Never create temp files like `payload.json`, `rewrite_app.py`, `update_*.js`
- Save a memory after completing significant work using the command above

---

*Managed by Stackbox · Do not edit this file*
"#
    ))
}

async fn build_memory_context(runbox_id: &str) -> String {
    // Pull recent memories — failures first, then decisions, then rest
    let all = match crate::memory::memories_for_runbox(runbox_id).await {
        Ok(m) => m,
        Err(_) => return String::new(),
    };

    if all.is_empty() { return String::new(); }

    // Separate by priority
    let failures:    Vec<_> = all.iter().filter(|m| m.tags.contains("failure")).take(3).collect();
    let decisions:   Vec<_> = all.iter().filter(|m| m.tags.contains("decision")).take(3).collect();
    let git_history: Vec<_> = all.iter().filter(|m| m.agent_name == "git").take(5).collect();
    let recent:      Vec<_> = all.iter()
        .filter(|m| m.agent_name != "git" && !m.tags.contains("failure") && !m.tags.contains("decision"))
        .take(3).collect();

    let mut parts: Vec<String> = Vec::new();

    if !failures.is_empty() {
        parts.push("### ⚠ Known Failures".to_string());
        for m in &failures {
            parts.push(format!("- {}", m.content.lines().next().unwrap_or("").trim()));
        }
        parts.push(String::new());
    }

    if !decisions.is_empty() {
        parts.push("### 🔷 Prior Decisions".to_string());
        for m in &decisions {
            parts.push(format!("- {}", m.content.lines().next().unwrap_or("").trim()));
        }
        parts.push(String::new());
    }

    if !git_history.is_empty() {
        parts.push("### 📜 Recent Git History".to_string());
        for m in &git_history {
            parts.push(format!("- {}", m.content.lines().next().unwrap_or("").trim()));
        }
        parts.push(String::new());
    }

    if !recent.is_empty() {
        parts.push("### 🧠 Recent Context".to_string());
        for m in &recent {
            parts.push(format!("- {}", m.content.lines().next().unwrap_or("").trim()));
        }
        parts.push(String::new());
    }

    if parts.is_empty() { return String::new(); }

    format!("## Supercontext — What You Need to Know\n\n{}\n\n", parts.join("\n"))
}