// src-tauri/src/workspace/context.rs

use crate::agent::kind::AgentKind;

pub const MEMORY_PORT: u16 = 7547;

pub async fn rewrite_context(
    db:         &crate::db::Db,
    runbox_id:  &str,
    session_id: &str,
    cwd:        &str,
    agent:      &AgentKind,
) -> Result<(), String> {
    let content = build(db, runbox_id, session_id, cwd, agent).await?;
    let path    = std::path::Path::new(cwd).join(".stackbox-context.md");
    std::fs::write(&path, &content).map_err(|e| format!("write context: {e}"))?;
    Ok(())
}

pub async fn build(
    _db:        &crate::db::Db,
    runbox_id:  &str,
    session_id: &str,
    cwd:        &str,
    agent:      &AgentKind,
) -> Result<String, String> {
    let port       = MEMORY_PORT;
    let short_sid  = &session_id[..session_id.len().min(8)];
    let agent_name = agent.display_name();

    Ok(format!(
r#"# Stackbox Agent Instructions

> You are: **{agent_name}** · session `{short_sid}` · runbox `{runbox_id}`
> Working directory: `{cwd}`

---

## Before You Start

Run this before editing any files:

```powershell
git add -A
```

This lets Stackbox track your changes (additions AND deletions).

---

## Saving Memories

After completing work, save a memory with this PowerShell command:

```powershell
Invoke-RestMethod -Uri "http://localhost:{port}/memory" -Method Post -ContentType "application/json" -Body (ConvertTo-Json @{{ runbox_id="{runbox_id}"; content="What you did, which files changed, any known issues." }})
```

Replace the `content` value with your actual summary (1–3 sentences).
Do NOT use `curl` or `memory_write` — use `Invoke-RestMethod` as shown above.

---

## Rules

- Always run `git add -A` before editing files
- Never create temp files like `payload.json`, `rewrite_app.py`, `update_*.js`
- Save a memory after completing significant work using the command above

---

*Managed by Stackbox · Do not edit this file*
"#
    ))
}