// src-tauri/src/workspace/context.rs
// Supercontext V2 — build() calls injector for ranked context block.

use crate::agent::kind::AgentKind;

pub const MEMORY_PORT: u16 = 7547;

pub async fn rewrite_context(
    db:         &crate::db::Db,
    runbox_id:  &str,
    session_id: &str,
    cwd:        &str,
    agent:      &AgentKind,
) -> Result<(), String> {
    let content = build(db, runbox_id, session_id, cwd, agent).await?;
    let path    = std::path::Path::new(cwd).join(".stackbox-context.md");
    std::fs::write(&path, &content).map_err(|e| format!("write context: {e}"))?;
    Ok(())
}

pub async fn build(
    _db:        &crate::db::Db,
    runbox_id:  &str,
    session_id: &str,
    cwd:        &str,
    agent:      &AgentKind,
) -> Result<String, String> {
    let port       = MEMORY_PORT;
    let short_sid  = &session_id[..session_id.len().min(8)];
    let agent_name = agent.display_name();

    let pane_port: u16 = {
        let mut hash: u32 = 0x811c9dc5;
        for b in runbox_id.as_bytes() { hash ^= *b as u32; hash = hash.wrapping_mul(0x01000193); }
        3100u16 + (hash % 900) as u16
    };

    // ── Ranked memory context via injector ────────────────────────────────────
    let memory_block = if *agent != AgentKind::Shell {
        let block = crate::agent::injector::build_context(runbox_id, "").await;
        if block.trim().is_empty() {
            build_first_session_context(cwd).await
        } else {
            format!("## Supercontext — Your Memory\n\n{block}\n")
        }
    } else {
        String::new()
    };

    Ok(format!(
r#"# Stackbox Agent Instructions

> You are: **{agent_name}** · session `{short_sid}` · runbox `{runbox_id}`
> Working directory: `{cwd}`

{memory_block}
---

## Memory Tools — Use These

You have 5 MCP tools for memory. Use them.

**At session start — call this FIRST:**
```
memory_context(task="describe what you're about to do")
```
Returns: goal, blockers (dead ends — skip), failures (don't re-break), env facts, codebase map.

**When you hit an error you can't solve:**
```
memory_write(content="Error: X. Tried: Y, Z. Do not retry Y or Z.", memory_type="blocker")
```

**When you fix something:**
```
memory_resolve(blocker_description="...", fix="root cause + exact fix")
```

**When you learn an env fact:**
```
memory_write(content="node=working\npy=broken\nport={pane_port}", memory_type="environment")
```

**When user tells you what to build:**
```
memory_goal(goal="...")
```

**When you need something specific:**
```
memory_search(query="port 3836")
```

---

## Before You Start

```powershell
git add -A
```

## Rules

- Call `memory_context` before writing any code — every time
- Your app port is **{pane_port}** — use `$env:PORT` or hardcode {pane_port}
- Never create temp files like `payload.json`, `rewrite_app.py`
- Write a `session` memory before ending — what changed, what's still open
- Env facts: key=value format only. Never prose.

---

*Managed by Stackbox · Do not edit this file*
"#
    ))
}

async fn build_first_session_context(cwd: &str) -> String {
    use crate::git::repo::git;
    let log      = git(&["log", "--oneline", "--no-merges", "-20"], cwd, None).unwrap_or_default();
    let status   = git(&["status", "--short"], cwd, None).unwrap_or_default();
    let branches = git(&["branch", "-a", "--format=%(refname:short)"], cwd, None).unwrap_or_default();

    if log.is_empty() && status.is_empty() { return String::new(); }

    let mut parts = vec!["## Project Context — First Session\n".to_string()];

    if !log.is_empty() {
        parts.push("### Recent Commits".to_string());
        for line in log.lines().take(15) {
            if !line.trim().is_empty() { parts.push(format!("- {}", line.trim())); }
        }
        parts.push(String::new());
    }

    if !branches.is_empty() {
        let blist: Vec<&str> = branches.lines().map(|b| b.trim()).filter(|b| !b.is_empty()).take(8).collect();
        if !blist.is_empty() { parts.push(format!("### Branches: {}", blist.join(", "))); parts.push(String::new()); }
    }

    if !status.is_empty() {
        let dirty: Vec<&str> = status.lines().take(8).collect();
        if !dirty.is_empty() {
            parts.push("### Uncommitted Changes".to_string());
            for l in dirty { parts.push(format!("- {}", l.trim())); }
        }
    }

    format!("{}\n\n", parts.join("\n"))
}